/***********************************************************************************************************************************************/
/********************************* List clientMonteCarloMapping:user_IP_addr:user_port:queryId ************************************************/ 
/**********************************************************************************************************************************************/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <hiredis/hiredis.h>
#define HOSTNAME "127.0.0.1"
#define PORT 6379
#define NAME "clientMonteCarloMapping"
#define MAX_LENGTH 100


/**
 * This function adds the subsolutions to the list for the given user IP address, user port and user query id.
 * @param user_IP_addr is the IP address of the user that is the input.
 * @param user_port is the port number that the user connects to the master that is the input.
 * @param queryId is the user query identifier that is the input.
 * @param subsoln is the number of circle points generated by the client.
 */
void clientMonteCarloMapping_set(char *user_IP_addr, int user_port, int queryId, int subsoln)
{
    redisContext *c;
    redisReply *reply;

    /* HOSTNAME and PORT of the redis-server */
    c = redisConnect(HOSTNAME, PORT);

    if (c == NULL || c->err) {
        if (c) {
            printf("Connection error: %s\n", c->errstr);
            redisFree(c);
        } else {
            printf("Connection error: can't allocate redis context\n");
        }
        exit(1);
    }

    /* PING server */
    reply = redisCommand(c,"PING");
    printf("PING: %s\n", reply->str);
    freeReplyObject(reply);

    /* Add the subsolution to the start of the list clientMonteCarloMapping:user_IP_addr:user_port:queryId */
    reply = redisCommand(c,"LPUSH %s:%s:%d:%d %d", NAME, user_IP_addr, user_port, queryId, subsoln);
    freeReplyObject(reply);

    redisFree(c);
}


/**
 * This function gets list size and contents of the list for the given user IP address, user port and user query id.
 * @param user_IP_addr is the IP address of the user that is the input.
 * @param user_port is the port number of user that is the input.
 * @param queryId is the user query identifier that is the input.
 * @param total_records is the list size that we want to retrieve.
 * @param subsoln_arr is the contents of the array that we want to retrieve.
 */
void clientMonteCarloMapping_get(char *user_IP_addr, int user_port, int queryId, int *total_records, int *subsoln_arr)
{
    redisContext *c;
    redisReply *reply;
    unsigned int j;
    int n=0;

    /* HOSTNAME and PORT of the redis-server */
    c = redisConnect(HOSTNAME, PORT);
    
    if (c == NULL || c->err) {
        if (c) {
            printf("Connection error: %s\n", c->errstr);
            redisFree(c);
        } else {
            printf("Connection error: can't allocate redis context\n");
        }
        exit(1);
    }

    /* PING server */
    reply = redisCommand(c,"PING");
    printf("PING: %s\n", reply->str);
    freeReplyObject(reply);

    /* get the contents of the list and the list size for clientMonteCarloMapping:user_IP_addr:user_port:queryId */
    reply = redisCommand(c,"LRANGE %s:%s:%d:%d 0 -1", NAME, user_IP_addr, user_port, queryId);
    if (reply->type == REDIS_REPLY_ARRAY) {
        *total_records = reply->elements;
        for (j = 0; j < *total_records; j++) {
            subsoln_arr[n++] = atoi(reply->element[j]->str);
        }
    }
    freeReplyObject(reply);
    redisFree(c);
}


/* Sample driver code */
/*int main()
{    

    int *total_records = NULL, *subsoln_arr = NULL;   
    unsigned int j;
    total_records = (int*) malloc(sizeof(int));
    subsoln_arr = (int*) malloc(sizeof(int)*MAX_LENGTH);
   
    clientMonteCarloMapping_set("1.1.1.5", 1020, 1, 100);
    clientMonteCarloMapping_set("1.1.1.5", 1020, 1, 200);
    clientMonteCarloMapping_set("1.1.1.5", 1020, 1, 300);
    clientMonteCarloMapping_set("1.1.1.5", 1020, 1, 400);

    printf("\n============ Getting clientMonteCarloMapping information ==============\n");
    clientMonteCarloMapping_get("1.1.1.5", 1020, 1, total_records, subsoln_arr);
    printf(" total_records: %d\n=================================\n", *total_records);
    for(j=0; j<*total_records; j++)
	printf("%d ", subsoln_arr[j]);
    printf("\n");
    
    free(total_records);
    free(subsoln_arr);

    return 0;
}*/












